server.port: 8080
eureka.client.service-url.defaultZone: http://localhost:8761/eureka
jwt.secretKey: asdfuasjf9a8s8atofd89ihq34kljruyf98ayshcskdhfioafsuyfdcjha890sduf

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

spring:
  application.name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: ${USER_SERVICE_URL:lb://USER-SERVICE}
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2

        - id: post-service
          uri: ${POST_SERVICE_URL:lb://POST-SERVICE}
          predicates:
            - Path=/api/v1/posts/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter

        - id: connection-service
          uri: ${CONNECTIONS_SERVICE_URL:lb://CONNECTION-SERVICE}
          predicates:
            - Path=/api/v1/connections/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter