apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
spec:
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
    spec:
      containers:
      - name: post-service
        image: harsh876/linkedln-post-service
        imagePullPolicy: Always
        resources:
          limits:
            memory: "400Mi"
            cpu: "200m"
          requests:
            memory: "200Mi"
            cpu: "100m"
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: k8s
          - name: DB_USERNAME
            value: postgres
          - name: DB_PASSWORD
            value: rootroot
          - name: DB_SERVER
            value: post-db
          - name: DB_NAME
            value: postDB
        ports:
        - containerPort: 9010

---

  apiVersion: v1
  kind: Service
  metadata:
    name: post-service
  spec:
    selector:
      app: post-service
    ports:
    - port: 80
      targetPort: 9010
  