spring.application.name: uploaderService

server.servlet.context-path: /uploads
server.port: 9050

eureka.client.service-url.defaultZone: http://localhost:8761/eureka/

cloudinary:
  cloud-name: 
  api-key: 
  api-secret: 

gcloud:
  storage-bucket-name: 
  storage-access-key: 
  